import { Article, Episode, Startup, User, Comment } from '../types';

export const articles: Article[] = [
  {
    id: '1',
    slug: 'karachi-startup-raises-2.5m-seed-round',
    title: 'Karachi-based Startup Raises $2.5M Seed Round',
    excerpt: 'A Karachi-based fintech startup has secured $2.5 million in seed funding to expand its digital payment solutions across Pakistan.',
    content: 'In a significant development for Pakistan\'s fintech ecosystem, a Karachi-based startup has successfully closed a $2.5 million seed funding round. The investment was led by prominent venture capital firms with participation from angel investors. The startup plans to use the funds to expand its digital payment infrastructure and reach underserved communities in rural Pakistan. This marks the third major fintech investment in Karachi this quarter, signaling growing confidence in Pakistan\'s digital economy. The company\'s CEO stated that they aim to onboard 100,000 merchants by the end of 2026.',
    category: 'startups',
    subcategory: 'Fintech',
    featuredImage: '/images/articles/karachi-startup.jpg',
    author: { name: 'Ahmed Khan', avatar: '/avatars/ahmed.jpg', role: 'Senior Writer' },
    publishedAt: '2026-08-20T10:00:00Z',
    readTime: 4,
    views: 12500,
    tags: ['fintech', 'karachi', 'seed-funding', 'startups'],
    isFeatured: true,
  },
  {
    id: '2',
    slug: 'nitb-launches-new-cybersecurity-framework',
    title: 'NITB Launches New Cybersecurity Framework for Government Agencies',
    excerpt: 'The National IT Board has unveiled a comprehensive cybersecurity framework to protect government digital infrastructure.',
    content: 'The National IT Board (NITB) has officially launched a new cybersecurity framework designed to enhance the security of government digital systems. The framework includes mandatory security protocols, incident response procedures, and regular audit requirements. This initiative comes in response to increasing cyber threats targeting government institutions. The framework aligns with international standards while addressing Pakistan-specific security challenges. All government agencies have been given six months to achieve compliance.',
    category: 'cybersecurity',
    featuredImage: '/images/articles/nitb-cybersecurity.jpg',
    author: { name: 'Fatima Ali', avatar: '/avatars/fatima.jpg', role: 'Security Analyst' },
    publishedAt: '2026-08-19T08:30:00Z',
    readTime: 5,
    views: 8900,
    tags: ['cybersecurity', 'government', 'NITB', 'framework'],
    isBreaking: true,
  },
  {
    id: '3',
    slug: 'ai-transforming-healthcare-pakistan',
    title: 'How AI is Transforming Healthcare in Pakistan',
    excerpt: 'Artificial intelligence applications are revolutionizing healthcare delivery from diagnostics to treatment planning.',
    content: 'Artificial intelligence is making significant inroads into Pakistan\'s healthcare sector. From AI-powered diagnostic tools in rural clinics to machine learning algorithms predicting disease outbreaks, the technology is transforming how healthcare is delivered. Several hospitals in Lahore and Islamabad have implemented AI systems that can analyze medical images with accuracy comparable to specialist doctors. The government has also announced plans to establish AI research centers focused on healthcare applications.',
    category: 'ai-cloud',
    featuredImage: '/images/articles/ai-healthcare.jpg',
    author: { name: 'Dr. Hassan Malik', avatar: '/avatars/hassan.jpg', role: 'Tech Contributor' },
    publishedAt: '2026-08-18T14:00:00Z',
    readTime: 6,
    views: 15200,
    tags: ['AI', 'healthcare', 'machine-learning', 'digital-health'],
    isFeatured: true,
  },
  {
    id: '4',
    slug: 'pakistan-5g-trials-begin-lahore',
    title: 'Pakistan 5G Trials Begin in Lahore',
    excerpt: 'Telecom operators have started 5G trials in Lahore, marking a new era of high-speed connectivity in Pakistan.',
    content: 'Pakistan has officially begun 5G trials in Lahore, with major telecom operators testing the next-generation wireless technology. The trials are being conducted in select areas of the city, with speeds reaching up to 10 Gbps in initial tests. The successful implementation of 5G is expected to boost Pakistan\'s digital economy and enable new technologies like autonomous vehicles and smart cities. The PTA has allocated spectrum for testing and expects commercial 5G services to launch by mid-2027.',
    category: 'it-news',
    featuredImage: '/images/articles/5g-pakistan.jpg',
    author: { name: 'Usman Raza', avatar: '/avatars/usman.jpg', role: 'Tech Reporter' },
    publishedAt: '2026-08-17T09:15:00Z',
    readTime: 4,
    views: 22000,
    tags: ['5G', 'telecom', 'lahore', 'connectivity'],
  },
  {
    id: '5',
    slug: 'review-iphone-17-pro-max',
    title: 'iPhone 17 Pro Max Review: Is It Worth the Upgrade?',
    excerpt: 'We take an in-depth look at Apple\'s latest flagship and whether it justifies the premium price tag.',
    content: 'Apple\'s iPhone 17 Pro Max brings significant improvements in camera technology, battery life, and processing power. The new A19 Bionic chip delivers unprecedented performance, while the upgraded camera system produces stunning photos even in low light. However, at its premium price point, is it worth upgrading from the previous generation? Our comprehensive review examines every aspect of this device to help you make an informed decision.',
    category: 'reviews',
    featuredImage: '/images/articles/iphone-review.jpg',
    author: { name: 'Sara Malik', avatar: '/avatars/sara.jpg', role: 'Review Editor' },
    publishedAt: '2026-08-16T11:00:00Z',
    readTime: 8,
    views: 34500,
    tags: ['apple', 'iphone', 'review', 'smartphone'],
    isFeatured: true,
  },
  {
    id: '6',
    slug: 'pakistan-cyber-attack-on-bank',
    title: 'Major Cyber Attack Targets Pakistani Banking System',
    excerpt: 'A sophisticated cyber attack attempted to compromise multiple banks\' online systems before being detected.',
    content: 'Pakistani cybersecurity authorities have thwarted a major cyber attack targeting the banking system. The attack, which originated from overseas, attempted to exploit vulnerabilities in online banking platforms. Quick action by the State Bank\'s cybersecurity team prevented any financial losses. The incident has prompted banks to enhance their security measures and the SBP to issue new cybersecurity guidelines for the financial sector.',
    category: 'cybersecurity',
    featuredImage: '/images/articles/bank-cyberattack.jpg',
    author: { name: 'Bilal Ahmed', avatar: '/avatars/bilal.jpg', role: 'Security Correspondent' },
    publishedAt: '2026-08-15T16:45:00Z',
    readTime: 5,
    views: 18700,
    tags: ['cybersecurity', 'banking', 'attack', 'finance'],
  },
  {
    id: '7',
    slug: 'islamabad-cloud-computing-hub',
    title: 'Islamabad to Become Pakistan\'s First Cloud Computing Hub',
    excerpt: 'The government announces plans to establish a state-of-the-art cloud computing facility in the capital.',
    content: 'The Ministry of IT has announced plans to develop Islamabad into Pakistan\'s first dedicated cloud computing hub. The facility will provide cloud services to government agencies, businesses, and startups at competitive rates. The project is expected to create over 5,000 jobs and attract international tech companies to set up operations in Pakistan. Construction is set to begin in early 2027, with the facility expected to be operational by 2028.',
    category: 'ai-cloud',
    featuredImage: '/images/articles/cloud-hub.jpg',
    author: { name: 'Ahmed Khan', avatar: '/avatars/ahmed.jpg', role: 'Senior Writer' },
    publishedAt: '2026-08-14T12:30:00Z',
    readTime: 4,
    views: 9800,
    tags: ['cloud', 'islamabad', 'infrastructure', 'government'],
  },
  {
    id: '8',
    slug: 'lahore-startup-revolutionizes-agriculture',
    title: 'Lahore Startup Revolutionizes Agriculture with IoT Sensors',
    excerpt: 'A Lahore-based startup is using IoT technology to help farmers optimize irrigation and increase crop yields.',
    content: 'A innovative Lahore-based startup has developed IoT sensors that are transforming agriculture in Punjab. The sensors monitor soil moisture, temperature, and nutrient levels, providing farmers with real-time data through a mobile app. Early adopters report 30% water savings and 20% increase in crop yields. The startup has already partnered with agricultural departments in three provinces and plans to expand nationwide by 2027.',
    category: 'startups',
    subcategory: 'AgriTech',
    featuredImage: '/images/articles/agritech-startup.jpg',
    author: { name: 'Fatima Ali', avatar: '/avatars/fatima.jpg', role: 'Security Analyst' },
    publishedAt: '2026-08-13T10:00:00Z',
    readTime: 5,
    views: 7600,
    tags: ['agritech', 'IoT', 'lahore', 'farming'],
  },
  {
    id: '9',
    slug: 'google-opens-office-karachi',
    title: 'Google Opens New Office in Karachi',
    excerpt: 'Tech giant Google has inaugurated its new Pakistan headquarters in Karachi\'s Shaheed-e-Millat Road.',
    content: 'Google has officially opened its new Pakistan headquarters in Karachi. The office, which will house over 200 employees, will focus on developing solutions for the Pakistani market and supporting local startups. The inauguration ceremony was attended by government officials and tech industry leaders. Google\'s Pakistan head stated that the company plans to invest $100 million in Pakistani startups over the next three years.',
    category: 'it-news',
    featuredImage: '/images/articles/google-office.jpg',
    author: { name: 'Usman Raza', avatar: '/avatars/usman.jpg', role: 'Tech Reporter' },
    publishedAt: '2026-08-12T09:00:00Z',
    readTime: 3,
    views: 28900,
    tags: ['google', 'karachi', 'international', 'investment'],
  },
  {
    id: '10',
    slug: 'review-macbook-pro-m5',
    title: 'MacBook Pro M5 Review: Power Meets Portability',
    excerpt: 'Apple\'s latest MacBook Pro with M5 chip sets new standards for professional laptops.',
    content: 'The MacBook Pro M5 represents a significant leap in laptop performance. With its new M5 chip, the laptop delivers desktop-level performance in a portable form factor. The improved battery life, stunning Liquid Retina XDR display, and enhanced audio make it the ultimate professional laptop. However, the high price and limited port selection may be drawbacks for some users.',
    category: 'reviews',
    featuredImage: '/images/articles/macbook-review.jpg',
    author: { name: 'Sara Malik', avatar: '/avatars/sara.jpg', role: 'Review Editor' },
    publishedAt: '2026-08-11T14:30:00Z',
    readTime: 7,
    views: 21300,
    tags: ['apple', 'macbook', 'review', 'laptop'],
  },
  {
    id: '11',
    slug: 'ai-education-revolution-pakistan',
    title: 'AI-Powered Learning Platforms Transform Education in Pakistan',
    excerpt: 'Adaptive learning technologies are personalizing education for millions of Pakistani students.',
    content: 'Artificial intelligence is revolutionizing education in Pakistan through adaptive learning platforms that personalize content for each student. These platforms analyze learning patterns and adjust difficulty levels in real-time, helping students learn at their own pace. Several EdTech startups have reported significant improvements in student performance, with some seeing 40% better test scores. The government is considering integrating these platforms into public schools.',
    category: 'ai-cloud',
    featuredImage: '/images/articles/ai-education.jpg',
    author: { name: 'Dr. Hassan Malik', avatar: '/avatars/hassan.jpg', role: 'Tech Contributor' },
    publishedAt: '2026-08-10T11:15:00Z',
    readTime: 5,
    views: 13400,
    tags: ['AI', 'education', 'edtech', 'learning'],
  },
  {
    id: '12',
    slug: 'pakistan-data-protection-law',
    title: 'Pakistan Passes Comprehensive Data Protection Law',
    excerpt: 'New legislation establishes strict rules for data collection, storage, and processing in Pakistan.',
    content: 'The Pakistani parliament has passed a comprehensive data protection law that establishes strict rules for how companies collect, store, and process personal data. The law, which takes effect in 2027, gives citizens greater control over their data and imposes heavy penalties for violations. Companies have 18 months to comply with the new requirements, which include mandatory data protection officers and breach notification procedures.',
    category: 'it-news',
    featuredImage: '/images/articles/data-protection.jpg',
    author: { name: 'Bilal Ahmed', avatar: '/avatars/bilal.jpg', role: 'Security Correspondent' },
    publishedAt: '2026-08-09T15:00:00Z',
    readTime: 6,
    views: 16700,
    tags: ['data-protection', 'privacy', 'law', 'regulation'],
  },
  {
    id: '13',
    slug: 'peshawar-tech-park-inauguration',
    title: 'Peshawar Tech Park Inaugurated to Boost IT Exports',
    excerpt: 'Khyber Pakhtunkhwa\'s new tech park aims to create 10,000 jobs and boost IT exports.',
    content: 'The Khyber Pakhtunkhwa government has inaugurated a state-of-the-art technology park in Peshawar. The facility, built at a cost of PKR 5 billion, includes co-working spaces, incubation centers, and training facilities. The tech park is expected to create 10,000 direct jobs and significantly boost the province\'s IT exports. Several international tech companies have already signed agreements to establish offices in the park.',
    category: 'startups',
    subcategory: 'Infrastructure',
    featuredImage: '/images/articles/peshawar-techpark.jpg',
    author: { name: 'Ahmed Khan', avatar: '/avatars/ahmed.jpg', role: 'Senior Writer' },
    publishedAt: '2026-08-08T10:45:00Z',
    readTime: 4,
    views: 6200,
    tags: ['tech-park', 'peshawar', 'KP', 'infrastructure'],
  },
  {
    id: '14',
    slug: 'samsung-galaxy-s26-review',
    title: 'Samsung Galaxy S26 Ultra Review: Android\'s Finest',
    excerpt: 'Samsung\'s latest flagship combines cutting-edge AI features with stunning hardware.',
    content: 'The Samsung Galaxy S26 Ultra sets a new standard for Android smartphones. With its advanced AI features, including real-time translation and intelligent photo editing, combined with the powerful Snapdragon 8 Gen 4 processor, it offers an unparalleled user experience. The improved S Pen and quad-camera system make it the most versatile smartphone on the market.',
    category: 'reviews',
    featuredImage: '/images/articles/samsung-review.jpg',
    author: { name: 'Sara Malik', avatar: '/avatars/sara.jpg', role: 'Review Editor' },
    publishedAt: '2026-08-07T13:00:00Z',
    readTime: 6,
    views: 19800,
    tags: ['samsung', 'galaxy', 'review', 'android'],
  },
];

export const episodes: Episode[] = [
  {
    id: '1',
    slug: 'startup-founders-panel-2026-trends',
    title: 'Startup Founders Panel: 2026 Trends',
    description: 'Leading Pakistani startup founders discuss emerging trends, funding landscape, and growth strategies for 2026.',
    youtubeId: 'dQw4w9WgXcQ',
    guest: 'Muhammad Furqan, Zain Abid, Asif Jafri',
    duration: '1:45:30',
    publishedAt: '2026-08-18T18:00:00Z',
  },
  {
    id: '2',
    slug: 'cybersecurity-experts-roundtable',
    title: 'Cybersecurity Experts Roundtable',
    description: 'Top cybersecurity professionals discuss the latest threats facing Pakistani organizations and how to mitigate them.',
    youtubeId: 'dQw4w9WgXcQ',
    guest: 'Dr. Syed Akif Raza, Usman Shaukat',
    duration: '1:20:15',
    publishedAt: '2026-08-11T18:00:00Z',
  },
  {
    id: '3',
    slug: 'ai-revolution-in-pakistan',
    title: 'The AI Revolution in Pakistan',
    description: 'Exploring how artificial intelligence is being adopted across industries in Pakistan.',
    youtubeId: 'dQw4w9WgXcQ',
    guest: 'Dr. Faisal Khan, Nabeel A. Hashmi',
    duration: '1:55:45',
    publishedAt: '2026-08-04T18:00:00Z',
  },
  {
    id: '4',
    slug: 'fintech-future-of-payments',
    title: 'Fintech: Future of Digital Payments',
    description: 'How digital payments are transforming commerce and financial inclusion in Pakistan.',
    youtubeId: 'dQw4w9WgXcQ',
    guest: 'JazzCash CEO, SadaPay Founder',
    duration: '1:30:00',
    publishedAt: '2026-07-28T18:00:00Z',
  },
  {
    id: '5',
    slug: 'women-in-tech-pakistan',
    title: 'Women Leading Tech in Pakistan',
    description: 'Celebrating and discussing the contributions of women in Pakistan\'s technology sector.',
    youtubeId: 'dQw4w9WgXcQ',
    guest: 'Jehan Ara, Saira Siddiqui, Dr. Najma-min-Hejazi',
    duration: '2:00:10',
    publishedAt: '2026-07-21T18:00:00Z',
  },
  {
    id: '6',
    slug: 'cloud-adoption-pakistani-businesses',
    title: 'Cloud Adoption in Pakistani Businesses',
    description: 'How local businesses are migrating to cloud infrastructure and the challenges they face.',
    youtubeId: 'dQw4w9WgXcQ',
    guest: 'AWS Pakistan Lead, Microsoft Pakistan Director',
    duration: '1:25:40',
    publishedAt: '2026-07-14T18:00:00Z',
  },
  {
    id: '7',
    slug: 'startup-pitch-competition-july-2026',
    title: 'Startup Pitch Competition: July 2026',
    description: 'Watch the top 5 startups from our incubator present their ideas to a panel of investors.',
    youtubeId: 'dQw4w9WgXcQ',
    guest: 'Multiple Startup Founders',
    duration: '2:15:00',
    publishedAt: '2026-07-07T18:00:00Z',
    isLive: true,
  },
];

export const startups: Startup[] = [
  {
    id: '1',
    name: 'Bazaar',
    sector: 'E-Commerce',
    funding: '$37.5M (Series B)',
    founder: 'Saad Jangda',
    founderTitle: 'CEO & Co-Founder',
    logo: '/logos/bazaar.png',
    description: 'Bazaar is a B2B e-commerce platform connecting manufacturers and retailers in Pakistan, simplifying the supply chain.',
    founded: '2020',
    website: 'https://bazaar.pk',
    employees: 450,
  },
  {
    id: '2',
    name: 'Bykea',
    sector: 'Transportation & Logistics',
    funding: '$33M (Series B)',
    founder: 'Muneeb Maayr',
    founderTitle: 'CEO & Co-Founder',
    logo: '/logos/bykea.png',
    description: 'Bykea is a ride-hailing and delivery platform serving millions of users across Pakistan with affordable mobility solutions.',
    founded: '2017',
    website: 'https://bykea.com',
    employees: 1200,
  },
  {
    id: '3',
    name: 'Airlift',
    sector: 'Transportation',
    funding: '$85M (Series B)',
    founder: 'Usman Gul',
    founderTitle: 'CEO & Co-Founder',
    logo: '/logos/airlift.png',
    description: 'Airlift operates a mass transit system using buses and provides on-demand delivery services in major Pakistani cities.',
    founded: '2018',
    website: 'https://airlift.com',
    employees: 800,
  },
  {
    id: '4',
    name: 'TelloTalk',
    sector: 'Communications',
    funding: '$5M (Series A)',
    founder: 'Babar Lakhani',
    founderTitle: 'CEO',
    logo: '/logos/tellotalk.png',
    description: 'TelloTalk is an enterprise messaging platform enabling businesses to communicate with customers through chatbots and AI.',
    founded: '2019',
    website: 'https://tellotalk.com',
    employees: 85,
  },
  {
    id: '5',
    name: 'SadaPay',
    sector: 'Fintech',
    funding: '$20.4M (Seed)',
    founder: 'Brandon Nieuwoudt',
    founderTitle: 'CEO & Co-Founder',
    logo: '/logos/sadapay.png',
    description: 'SadaPay is a digital banking platform offering fee-free debit cards and seamless international transactions for Pakistanis.',
    founded: '2019',
    website: 'https://sadapay.pk',
    employees: 150,
  },
  {
    id: '6',
    name: 'Fazal Technical Services',
    sector: 'Logistics',
    funding: '$15M (Series A)',
    founder: 'Bilal Raza',
    founderTitle: 'Founder & CEO',
    logo: '/logos/fazal.png',
    description: 'A leading last-mile delivery service connecting e-commerce businesses with customers across Pakistan.',
    founded: '2018',
    website: 'https://fazal.com',
    employees: 600,
  },
  {
    id: '7',
    name: 'Integry',
    sector: 'SaaS',
    funding: '$4.2M (Seed)',
    founder: 'Imtiaz Rastgar',
    founderTitle: 'CEO & Co-Founder',
    logo: '/logos/integry.png',
    description: 'Integry provides integration and automation tools that help SaaS companies connect their products with other apps.',
    founded: '2019',
    website: 'https://integry.io',
    employees: 60,
  },
  {
    id: '8',
    name: 'Bulbul',
    sector: 'E-Commerce',
    funding: '$6.2M (Series A)',
    founder: 'Ehsan Saya',
    founderTitle: 'CEO',
    logo: '/logos/bulbul.png',
    description: 'Bulbul is a live-streaming e-commerce platform that allows sellers to showcase products through interactive video sessions.',
    founded: '2019',
    website: 'https://bulbul.tv',
    employees: 120,
  },
];

export const users: User[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@ilmtech.pk',
    avatar: '/avatars/admin.jpg',
    role: 'admin',
    joinedAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Ahmed Khan',
    email: 'ahmed@ilmtech.pk',
    avatar: '/avatars/ahmed.jpg',
    role: 'editor',
    joinedAt: '2024-03-20',
  },
  {
    id: '3',
    name: 'Fatima Ali',
    email: 'fatima@ilmtech.pk',
    avatar: '/avatars/fatima.jpg',
    role: 'editor',
    joinedAt: '2024-06-10',
  },
  {
    id: '4',
    name: 'Usman Raza',
    email: 'usman@ilmtech.pk',
    avatar: '/avatars/usman.jpg',
    role: 'contributor',
    joinedAt: '2025-01-05',
  },
  {
    id: '5',
    name: 'Sara Malik',
    email: 'sara@ilmtech.pk',
    avatar: '/avatars/sara.jpg',
    role: 'contributor',
    joinedAt: '2025-04-12',
  },
];

export const comments: Comment[] = [
  {
    id: '1',
    articleId: '1',
    userId: '5',
    content: 'Great news for Pakistan\'s fintech ecosystem! The seed round will help them scale significantly.',
    createdAt: '2026-08-20T12:00:00Z',
    likes: 15,
  },
  {
    id: '2',
    articleId: '1',
    userId: '4',
    content: 'Karachi is becoming a real hub for tech investments. Exciting times ahead!',
    createdAt: '2026-08-20T13:30:00Z',
    likes: 8,
  },
  {
    id: '3',
    articleId: '2',
    userId: '3',
    content: 'Finally, a proper cybersecurity framework for government agencies. This was long overdue.',
    createdAt: '2026-08-19T10:00:00Z',
    likes: 22,
  },
  {
    id: '4',
    articleId: '2',
    userId: '1',
    content: 'The 6-month compliance timeline is aggressive. I hope agencies are prepared.',
    createdAt: '2026-08-19T11:15:00Z',
    likes: 12,
  },
  {
    id: '5',
    articleId: '3',
    userId: '2',
    content: 'AI in healthcare could save thousands of lives in rural areas where specialists are scarce.',
    createdAt: '2026-08-18T16:00:00Z',
    likes: 35,
  },
  {
    id: '6',
    articleId: '3',
    userId: '5',
    content: 'Would love to see more details about the specific AI algorithms being used.',
    createdAt: '2026-08-18T17:30:00Z',
    likes: 7,
  },
  {
    id: '7',
    articleId: '4',
    userId: '4',
    content: '5G in Lahore is a game changer. When can we expect it in other cities?',
    createdAt: '2026-08-17T11:00:00Z',
    likes: 18,
  },
  {
    id: '8',
    articleId: '4',
    userId: '2',
    content: 'The speed tests are impressive! 10 Gbps is incredible.',
    createdAt: '2026-08-17T12:45:00Z',
    likes: 14,
  },
  {
    id: '9',
    articleId: '5',
    userId: '3',
    content: 'The camera improvements sound amazing, but the price is still too high for most Pakistanis.',
    createdAt: '2026-08-16T14:00:00Z',
    likes: 25,
  },
  {
    id: '10',
    articleId: '5',
    userId: '1',
    content: 'Battery life improvements are what I care about most. How does it compare to the 16?',
    createdAt: '2026-08-16T15:30:00Z',
    likes: 9,
  },
];
