import { Article, Episode, Startup, Investor, User, Comment, Author, Tag } from '../types';

export const authors: Author[] = [
  {
    id: 'ahmed-khan',
    name: 'Ahmed Khan',
    email: 'ahmed@ilmtech.pk',
    avatar: 'https://i.pravatar.cc/150?u=ahmed-khan',
    role: 'Senior Writer',
    bio: 'Ahmed is a seasoned tech journalist with over 8 years of experience covering Pakistan\'s startup ecosystem and IT industry. He previously worked at Dawn News and brings deep insight into the country\'s digital transformation.',
    socialLinks: {
      twitter: 'https://twitter.com/ahmedkhan_tech',
      linkedin: 'https://linkedin.com/in/ahmedkhan',
    },
    articlesCount: 142,
  },
  {
    id: 'fatima-ali',
    name: 'Fatima Ali',
    email: 'fatima@ilmtech.pk',
    avatar: 'https://i.pravatar.cc/150?u=fatima-ali',
    role: 'Security Analyst',
    bio: 'Fatima is a certified cybersecurity professional and journalist covering data privacy, cyber threats, and government IT policy. She holds a Master\'s in Information Security from NUST.',
    socialLinks: {
      twitter: 'https://twitter.com/fatima_cyber',
      linkedin: 'https://linkedin.com/in/fatimaali',
    },
    articlesCount: 98,
  },
  {
    id: 'hassan-malik',
    name: 'Dr. Hassan Malik',
    email: 'hassan@ilmtech.pk',
    avatar: 'https://i.pravatar.cc/150?u=hassan-malik',
    role: 'Tech Contributor',
    bio: 'Dr. Hassan is an AI researcher and professor at LUMS who writes about artificial intelligence, machine learning, and cloud computing trends impacting Pakistan\'s industries.',
    socialLinks: {
      twitter: 'https://twitter.com/dr_hassan_ai',
      linkedin: 'https://linkedin.com/in/drhassanmalik',
    },
    articlesCount: 67,
  },
  {
    id: 'usman-raza',
    name: 'Usman Raza',
    email: 'usman@ilmtech.pk',
    avatar: 'https://i.pravatar.cc/150?u=usman-raza',
    role: 'Tech Reporter',
    bio: 'Usman covers telecom, 5G rollout, and infrastructure development in Pakistan. He is passionate about bridging the digital divide in underserved areas of the country.',
    socialLinks: {
      twitter: 'https://twitter.com/usmanraza_pk',
      linkedin: 'https://linkedin.com/in/usmanraza',
    },
    articlesCount: 85,
  },
  {
    id: 'sara-malik',
    name: 'Sara Malik',
    email: 'sara@ilmtech.pk',
    avatar: 'https://i.pravatar.cc/150?u=sara-malik',
    role: 'Review Editor',
    bio: 'Sara leads product reviews at IlmTech with a focus on smartphones, laptops, and consumer gadgets. Her detailed reviews have become a trusted resource for tech buyers in Pakistan.',
    socialLinks: {
      twitter: 'https://twitter.com/sarareviews_pk',
      linkedin: 'https://linkedin.com/in/saramalik',
    },
    articlesCount: 112,
  },
];

export const articles: Article[] = [
  {
    id: '1',
    slug: 'bykea-secures-series-c-funding-expansion',
    title: 'Bykea Secures $45M Series C to Expand Ride-Hailing and Logistics',
    excerpt: 'Karachi-based Bykea closes its largest funding round yet, led by Global Ventures, to expand operations across Pakistan.',
    content: 'Bykea, one of Pakistan\'s leading ride-hailing and logistics platforms, has announced the closure of a $45 million Series C funding round led by Global Ventures. The company plans to expand into 15 new cities, enhance its micro-finance offering, and scale its delivery fleet to 100,000 drivers.',
    category: 'startups',
    subcategory: 'Fintech',
    featuredImage: 'https://picsum.photos/seed/bykea-series-c/800/500',
    author: authors[0],
    publishedAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-08-21T08:30:00Z',
    readTime: 5,
    views: 18750,
    shares: 3420,
    tags: ['fintech', 'startup-funding', 'karachi', 'ride-hailing', 'series-c'],
    isFeatured: true,
    sources: [
      { label: 'Bykea Press Release', url: 'https://bykea.com/press' },
      { label: 'Global Ventures', url: 'https://globalventures.fund' },
    ],
  },
  {
    id: '2',
    slug: 'nitb-launches-new-cybersecurity-framework',
    title: 'NITB Launches Comprehensive Cybersecurity Framework for Government',
    excerpt: 'The National IT Board unveils a mandatory cybersecurity framework requiring all government agencies to comply within six months.',
    content: 'The National IT Board (NITB) has officially launched a comprehensive cybersecurity framework designed to enhance the security of government digital systems. The framework includes mandatory security protocols, incident response procedures, and zero-trust architecture guidelines.',
    category: 'cybersecurity',
    featuredImage: 'https://picsum.photos/seed/nitb-cybersecurity/800/500',
    author: authors[1],
    publishedAt: '2026-08-19T08:30:00Z',
    readTime: 6,
    views: 9200,
    shares: 1890,
    tags: ['cybersecurity', 'government', 'NITB', 'data-protection', 'policy'],
    isBreaking: true,
    sources: [
      { label: 'NITB Official', url: 'https://nitb.gov.pk' },
    ],
  },
  {
    id: '3',
    slug: 'ai-transforming-healthcare-pakistan',
    title: 'How AI is Transforming Healthcare Delivery in Pakistan',
    excerpt: 'From AI-powered diagnostics in rural clinics to predictive analytics, artificial intelligence is revolutionizing Pakistani healthcare.',
    content: 'Artificial intelligence is making significant inroads into Pakistan\'s healthcare sector. Several hospitals in Lahore and Islamabad have implemented AI systems that analyze medical images with accuracy comparable to specialist doctors.',
    category: 'ai-cloud',
    featuredImage: 'https://picsum.photos/seed/ai-healthcare-pk/800/500',
    author: authors[2],
    publishedAt: '2026-08-18T14:00:00Z',
    readTime: 7,
    views: 15200,
    shares: 2850,
    tags: ['AI', 'healthcare', 'machine-learning', 'digital-health', 'startups'],
    isFeatured: true,
  },
  {
    id: '4',
    slug: 'pakistan-5g-trials-begin-lahore',
    title: 'Pakistan Begins 5G Trials in Lahore with 10 Gbps Speeds',
    excerpt: 'Major telecom operators test next-generation 5G technology in Lahore, reaching unprecedented speeds in initial testing.',
    content: 'Pakistan has officially begun 5G trials in Lahore, with Jazz, Telenor, and Zong testing the next-generation wireless technology. Initial tests have shown speeds reaching up to 10 Gbps, with latency below 1 millisecond.',
    category: 'it-news',
    featuredImage: 'https://picsum.photos/seed/5g-pakistan-lahore/800/500',
    author: authors[3],
    publishedAt: '2026-08-17T09:15:00Z',
    readTime: 5,
    views: 24500,
    shares: 4200,
    tags: ['5G', 'telecom', 'lahore', 'connectivity', 'PTA'],
    sources: [
      { label: 'Pakistan Telecommunication Authority', url: 'https://pta.gov.pk' },
    ],
  },
  {
    id: '5',
    slug: 'review-iphone-17-pro-max',
    title: 'iPhone 17 Pro Max Review: The Ultimate Upgrade?',
    excerpt: 'Apple\'s flagship brings a new A19 Bionic chip, improved camera system, and all-day battery life \u2014 but at a steep price.',
    content: 'The iPhone 17 Pro Max represents Apple\'s most ambitious smartphone to date. The A19 Bionic chip delivers 40% faster performance than last year, while the new quad-camera system produces stunning photos. At PKR 349,000, it remains a premium proposition.',
    category: 'reviews',
    featuredImage: 'https://picsum.photos/seed/iphone17-review/800/500',
    author: authors[4],
    publishedAt: '2026-08-16T11:00:00Z',
    readTime: 9,
    views: 38200,
    shares: 5100,
    tags: ['apple', 'iphone', 'review', 'smartphone', 'mobile'],
    isFeatured: true,
  },
  {
    id: '6',
    slug: 'major-cyber-attack-targets-pakistani-banks',
    title: 'Sophisticated Cyber Attack Targets Multiple Pakistani Banks',
    excerpt: 'A coordinated attack on the banking system is thwarted by SBP\'s cybersecurity team, prompting new security guidelines.',
    content: 'Pakistani cybersecurity authorities have thwarted a major cyber attack targeting multiple banks\' online systems. The attack, which originated from a state-sponsored group, attempted to exploit zero-day vulnerabilities in online banking platforms.',
    category: 'cybersecurity',
    featuredImage: 'https://picsum.photos/seed/bank-cyberattack-pk/800/500',
    author: authors[1],
    publishedAt: '2026-08-15T16:45:00Z',
    readTime: 6,
    views: 21300,
    shares: 3670,
    tags: ['cybersecurity', 'banking', 'attack', 'finance', 'SBP'],
    sources: [
      { label: 'State Bank of Pakistan', url: 'https://sbp.org.pk' },
    ],
  },
  {
    id: '7',
    slug: 'islamabad-cloud-computing-hub-pakistan',
    title: 'Islamabad to Become Pakistan\'s First Dedicated Cloud Computing Hub',
    excerpt: 'The government invests PKR 25 billion to build a state-of-the-art cloud facility, creating 5,000+ jobs.',
    content: 'The Ministry of IT has announced plans to develop Islamabad into Pakistan\'s first dedicated cloud computing hub. The facility, backed by PKR 25 billion in government investment, will provide sovereign cloud services to government agencies and enterprises.',
    category: 'ai-cloud',
    featuredImage: 'https://picsum.photos/seed/cloud-hub-islamabad/800/500',
    author: authors[0],
    publishedAt: '2026-08-14T12:30:00Z',
    readTime: 5,
    views: 10500,
    shares: 1980,
    tags: ['cloud', 'islamabad', 'infrastructure', 'government', 'data-center'],
  },
  {
    id: '8',
    slug: 'lahore-startup-revolutionizes-agriculture-iot',
    title: 'Lahore Startup Revolutionizes Agriculture with IoT Sensors',
    excerpt: 'CropTech\'s smart sensors help farmers save 30% water and boost yields by 20% across Punjab.',
    content: 'A Lahore-based AgriTech startup has developed IoT sensors that are transforming agriculture in Punjab. The sensors monitor soil moisture, temperature, nutrient levels, and pest activity, providing farmers with real-time data.',
    category: 'startups',
    subcategory: 'AgriTech',
    featuredImage: 'https://picsum.photos/seed/agritech-iot-lahore/800/500',
    author: authors[0],
    publishedAt: '2026-08-13T10:00:00Z',
    readTime: 5,
    views: 8200,
    shares: 1560,
    tags: ['agritech', 'IoT', 'lahore', 'farming', 'sustainability'],
  },
  {
    id: '9',
    slug: 'google-opens-pakistan-hq-karachi',
    title: 'Google Opens Pakistan Headquarters in Karachi with $100M Startup Fund',
    excerpt: 'Tech giant inaugurates its Pakistan HQ and announces a $100 million fund for local startups over three years.',
    content: 'Google has officially opened its new Pakistan headquarters in Karachi\'s Shaheed-e-Millat Road. The office will house over 200 employees. Google announced a $100 million fund to invest in Pakistani startups over the next three years.',
    category: 'it-news',
    featuredImage: 'https://picsum.photos/seed/google-office-karachi/800/500',
    author: authors[3],
    publishedAt: '2026-08-12T09:00:00Z',
    readTime: 4,
    views: 31200,
    shares: 4890,
    tags: ['google', 'karachi', 'international', 'investment', 'startup-funding'],
  },
  {
    id: '10',
    slug: 'review-macbook-pro-m5-chip',
    title: 'MacBook Pro M5 Review: Desktop Power in a Laptop',
    excerpt: 'Apple\'s M5 chip delivers unprecedented performance, but the high price and limited ports may deter some buyers.',
    content: 'The MacBook Pro M5 represents a significant leap in laptop performance. The M5 chip delivers desktop-level performance in a portable form factor. Battery life exceeds 18 hours, and the six-speaker audio system is remarkable.',
    category: 'reviews',
    featuredImage: 'https://picsum.photos/seed/macbook-m5-review/800/500',
    author: authors[4],
    publishedAt: '2026-08-11T14:30:00Z',
    readTime: 8,
    views: 23800,
    shares: 3210,
    tags: ['apple', 'macbook', 'review', 'laptop', 'M5'],
  },
  {
    id: '11',
    slug: 'ai-powered-edtech-transforming-pakistan-education',
    title: 'AI-Powered EdTech Platforms Transform Education for 10M Students',
    excerpt: 'Adaptive learning technologies personalize education, with early results showing 40% improvement in test scores.',
    content: 'Artificial intelligence is revolutionizing education in Pakistan through adaptive learning platforms that personalize content for each student. The technology now reaches over 10 million students across 50,000 schools.',
    category: 'ai-cloud',
    featuredImage: 'https://picsum.photos/seed/ai-education-pk/800/500',
    author: authors[2],
    publishedAt: '2026-08-10T11:15:00Z',
    readTime: 6,
    views: 14500,
    shares: 2670,
    tags: ['AI', 'education', 'edtech', 'learning', 'social-impact'],
  },
  {
    id: '12',
    slug: 'pakistan-passes-data-protection-law-2026',
    title: 'Pakistan Passes Comprehensive Data Protection Law',
    excerpt: 'New legislation gives citizens control over personal data and imposes heavy penalties for violations.',
    content: 'The Pakistani parliament has passed a comprehensive data protection law establishing strict rules for how companies collect, store, and process personal data. Companies face fines of up to 4% of annual revenue for violations.',
    category: 'it-news',
    featuredImage: 'https://picsum.photos/seed/data-protection-law-pk/800/500',
    author: authors[1],
    publishedAt: '2026-08-09T15:00:00Z',
    readTime: 7,
    views: 17800,
    shares: 3120,
    tags: ['data-protection', 'privacy', 'law', 'regulation', 'policy'],
    sources: [
      { label: 'Ministry of IT & Telecom', url: 'https://moit.gov.pk' },
    ],
  },
  {
    id: '13',
    slug: 'peshawar-tech-park-inauguration',
    title: 'Peshawar Tech Park Inaugurated, Targets 10,000 Jobs',
    excerpt: 'KPK\'s PKR 5 billion tech park features co-working spaces, incubation centers, and training facilities.',
    content: 'The Khyber Pakhtunkhwa government has inaugurated a state-of-the-art technology park in Peshawar. Built at a cost of PKR 5 billion, the facility is expected to create 10,000 direct jobs.',
    category: 'startups',
    subcategory: 'Infrastructure',
    featuredImage: 'https://picsum.photos/seed/peshawar-techpark/800/500',
    author: authors[0],
    publishedAt: '2026-08-08T10:45:00Z',
    readTime: 5,
    views: 7100,
    shares: 1340,
    tags: ['tech-park', 'peshawar', 'KP', 'infrastructure', 'jobs'],
  },
  {
    id: '14',
    slug: 'samsung-galaxy-s26-ultra-review',
    title: 'Samsung Galaxy S26 Ultra Review: Android\'s New King',
    excerpt: 'Samsung\'s flagship combines cutting-edge AI features with a stunning 200MP camera and all-day battery.',
    content: 'The Samsung Galaxy S26 Ultra sets a new standard for Android smartphones. The Snapdragon 8 Gen 4 processor delivers exceptional performance, while the 200MP camera system captures incredible detail. At PKR 285,000, it offers better value than its Apple rival.',
    category: 'reviews',
    featuredImage: 'https://picsum.photos/seed/samsung-s26-review/800/500',
    author: authors[4],
    publishedAt: '2026-08-07T13:00:00Z',
    readTime: 8,
    views: 21500,
    shares: 3450,
    tags: ['samsung', 'galaxy', 'review', 'android', 'smartphone'],
  },
];

export const episodes: Episode[] = [
  {
    id: '1',
    slug: 'startup-founders-panel-2026-trends',
    title: 'Startup Founders Panel: 2026 Trends',
    description: 'Leading Pakistani startup founders discuss emerging trends, funding landscape, and growth strategies for 2026.',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://picsum.photos/seed/startup-panel-2026/640/360',
    guest: 'Muhammad Furqan, Zain Abid, Asif Jafri',
    guestTitle: 'CEOs of Top Pakistani Startups',
    duration: '1:45:30',
    publishedAt: '2026-08-18T18:00:00Z',
  },
  {
    id: '2',
    slug: 'cybersecurity-experts-roundtable',
    title: 'Cybersecurity Experts Roundtable',
    description: 'Top cybersecurity professionals discuss the latest threats facing Pakistani organizations.',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://picsum.photos/seed/cyber-roundtable/640/360',
    guest: 'Dr. Syed Akif Raza, Usman Shaukat',
    guestTitle: 'CISOs, Leading Banks',
    duration: '1:20:15',
    publishedAt: '2026-08-11T18:00:00Z',
  },
  {
    id: '3',
    slug: 'ai-revolution-in-pakistan',
    title: 'The AI Revolution in Pakistan',
    description: 'Exploring how artificial intelligence is being adopted across industries in Pakistan.',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://picsum.photos/seed/ai-revolution-pk/640/360',
    guest: 'Dr. Faisal Khan, Nabeel A. Hashmi',
    guestTitle: 'AI Researchers, NUST',
    duration: '1:55:45',
    publishedAt: '2026-08-04T18:00:00Z',
  },
  {
    id: '4',
    slug: 'fintech-future-of-payments',
    title: 'Fintech: Future of Digital Payments',
    description: 'How digital payments are transforming commerce and financial inclusion in Pakistan.',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://picsum.photos/seed/fintech-payments/640/360',
    guest: 'JazzCash CEO, SadaPay Founder',
    guestTitle: 'CEO, JazzCash & Founder, SadaPay',
    duration: '1:30:00',
    publishedAt: '2026-07-28T18:00:00Z',
  },
  {
    id: '5',
    slug: 'women-in-tech-pakistan',
    title: 'Women Leading Tech in Pakistan',
    description: 'Celebrating the contributions of women in Pakistan\'s technology sector.',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://picsum.photos/seed/women-tech-pk/640/360',
    guest: 'Jehan Ara, Saira Siddiqui',
    guestTitle: 'Founders & VC Partners',
    duration: '2:00:10',
    publishedAt: '2026-07-21T18:00:00Z',
  },
  {
    id: '6',
    slug: 'cloud-adoption-pakistani-businesses',
    title: 'Cloud Adoption in Pakistani Businesses',
    description: 'How local businesses are migrating to cloud infrastructure and the challenges they face.',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://picsum.photos/seed/cloud-adoption-pk/640/360',
    guest: 'AWS Pakistan Lead, Microsoft Pakistan Director',
    guestTitle: 'Country Directors, AWS & Microsoft',
    duration: '1:25:40',
    publishedAt: '2026-07-14T18:00:00Z',
  },
  {
    id: '7',
    slug: 'startup-pitch-competition-july-2026',
    title: 'Startup Pitch Competition: July 2026',
    description: 'Watch the top 5 startups from our incubator present their ideas to a panel of investors.',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://picsum.photos/seed/pitch-competition/640/360',
    guest: 'Multiple Startup Founders',
    guestTitle: 'Top 5 Incubator Startups',
    duration: '2:15:00',
    publishedAt: '2026-07-07T18:00:00Z',
    isLive: true,
  },
];

export const startups: Startup[] = [
  {
    id: '1',
    name: 'Bykea',
    slug: 'bykea',
    sector: 'Transportation & Logistics',
    city: 'Karachi',
    funding: '$85M+',
    fundingStage: 'Series C',
    founder: 'Muneeb Maayr',
    founderTitle: 'CEO & Co-Founder',
    logo: 'https://ui-avatars.com/api/?name=Bykea&background=37215F&color=fff&size=128&bold=true',
    description: 'Bykea is a ride-hailing, delivery, and financial services platform serving millions of users across Pakistan with affordable mobility and micro-finance solutions.',
    founded: '2017',
    website: 'https://bykea.com',
    employees: 1200,
    tags: ['fintech', 'mobility', 'gig-economy', 'microfinance'],
    fundingRounds: [
      { round: 'Seed', amount: '$2.1M', date: '2018-06', leadInvestor: 'i2i Ventures' },
      { round: 'Series A', amount: '$12M', date: '2019-11', leadInvestor: 'Sarmayacar' },
      { round: 'Series B', amount: '$33M', date: '2021-03', leadInvestor: 'Indus Valley Capital' },
      { round: 'Series C', amount: '$45M', date: '2026-08', leadInvestor: 'Global Ventures' },
    ],
    investors: ['Global Ventures', 'Indus Valley Capital', 'Sarmayacar', 'i2i Ventures'],
  },
  {
    id: '2',
    name: 'SadaPay',
    slug: 'sadapay',
    sector: 'Fintech',
    city: 'Karachi',
    funding: '$20.4M',
    fundingStage: 'Seed',
    founder: 'Brandon Nieuwoudt',
    founderTitle: 'CEO & Co-Founder',
    logo: 'https://ui-avatars.com/api/?name=SadaPay&background=00C9A7&color=fff&size=128&bold=true',
    description: 'SadaPay is a digital banking platform offering fee-free debit cards, seamless international transactions, and budgeting tools for Pakistanis.',
    founded: '2019',
    website: 'https://sadapay.pk',
    employees: 150,
    tags: ['digital-banking', 'fintech', 'neobank', 'payments'],
    fundingRounds: [
      { round: 'Pre-Seed', amount: '$1.8M', date: '2020-01', leadInvestor: 'Global Ventures' },
      { round: 'Seed', amount: '$20.4M', date: '2021-09', leadInvestor: 'Kingsway Capital' },
    ],
    investors: ['Kingsway Capital', 'Global Ventures', 'Kingsway GP Ltd'],
  },
  {
    id: '3',
    name: 'Bazaar',
    slug: 'bazaar',
    sector: 'E-Commerce',
    city: 'Lahore',
    funding: '$37.5M',
    fundingStage: 'Series B',
    founder: 'Saad Jangda',
    founderTitle: 'CEO & Co-Founder',
    logo: 'https://ui-avatars.com/api/?name=Bazaar&background=FF6B35&color=fff&size=128&bold=true',
    description: 'Bazaar is a B2B e-commerce platform connecting manufacturers and retailers in Pakistan, simplifying the supply chain for thousands of stores.',
    founded: '2020',
    website: 'https://bazaar.pk',
    employees: 450,
    tags: ['b2b', 'e-commerce', 'supply-chain', 'retail'],
    fundingRounds: [
      { round: 'Pre-Seed', amount: '$1.5M', date: '2020-06', leadInvestor: 'Indus Valley Capital' },
      { round: 'Seed', amount: '$6M', date: '2021-03', leadInvestor: 'Y Combinator' },
      { round: 'Series A', amount: '$16M', date: '2021-08', leadInvestor: 'Indus Valley Capital' },
      { round: 'Series B', amount: '$37.5M', date: '2022-04', leadInvestor: 'Sarmayacar' },
    ],
    investors: ['Sarmayacar', 'Indus Valley Capital', 'Y Combinator', 'Global Ventures'],
  },
  {
    id: '4',
    name: 'TAG Innovation',
    slug: 'tag-innovation',
    sector: 'Fintech',
    city: 'Lahore',
    funding: '$12M',
    fundingStage: 'Series A',
    founder: 'Talal Gondal',
    founderTitle: 'CEO & Co-Founder',
    logo: 'https://ui-avatars.com/api/?name=TAG+Innovation&background=1E88E5&color=fff&size=128&bold=true',
    description: 'TAG provides digital financial infrastructure enabling businesses to embed payments, lending, and insurance into their platforms through APIs.',
    founded: '2019',
    website: 'https://taginnovation.co',
    employees: 85,
    tags: ['embedded-finance', 'B2B', 'APIs', 'fintech-infrastructure'],
    fundingRounds: [
      { round: 'Seed', amount: '$3.5M', date: '2020-09', leadInvestor: 'i2i Ventures' },
      { round: 'Series A', amount: '$12M', date: '2022-01', leadInvestor: 'Fatima Gobi Ventures' },
    ],
    investors: ['Fatima Gobi Ventures', 'i2i Ventures', 'Global Ventures'],
  },
  {
    id: '5',
    name: 'Airlift',
    slug: 'airlift',
    sector: 'Transportation',
    city: 'Lahore',
    funding: '$85M',
    fundingStage: 'Series B',
    founder: 'Usman Gul',
    founderTitle: 'CEO & Co-Founder',
    logo: 'https://ui-avatars.com/api/?name=Airlift&background=43A047&color=fff&size=128&bold=true',
    description: 'Airlift operates mass transit systems and on-demand delivery services in major Pakistani cities, providing affordable urban mobility.',
    founded: '2018',
    website: 'https://airlift.com',
    employees: 800,
    tags: ['mass-transit', 'mobility', 'urban-transport', 'logistics'],
    fundingRounds: [
      { round: 'Seed', amount: '$2.2M', date: '2019-01', leadInvestor: 'Y Combinator' },
      { round: 'Series A', amount: '$12M', date: '2020-06', leadInvestor: 'Indus Valley Capital' },
      { round: 'Series B', amount: '$85M', date: '2021-11', leadInvestor: 'General Atlantic' },
    ],
    investors: ['General Atlantic', 'Indus Valley Capital', 'Y Combinator', 'Fatima Gobi Ventures'],
  },
  {
    id: '6',
    name: 'TelloTalk',
    slug: 'tellotalk',
    sector: 'Communications',
    city: 'Karachi',
    funding: '$5M',
    fundingStage: 'Series A',
    founder: 'Babar Lakhani',
    founderTitle: 'CEO',
    logo: 'https://ui-avatars.com/api/?name=TelloTalk&background=8E24AA&color=fff&size=128&bold=true',
    description: 'TelloTalk is an enterprise messaging platform enabling businesses to communicate with customers through chatbots, AI, and conversational commerce.',
    founded: '2019',
    website: 'https://tellotalk.com',
    employees: 85,
    tags: ['enterprise-messaging', 'chatbot', 'conversational-AI', 'B2B'],
    fundingRounds: [
      { round: 'Pre-Seed', amount: '$0.8M', date: '2019-05', leadInvestor: 'Sarmayacar' },
      { round: 'Series A', amount: '$5M', date: '2021-07', leadInvestor: 'Sarmayacar' },
    ],
    investors: ['Sarmayacar', 'i2i Ventures'],
  },
  {
    id: '7',
    name: 'Devsinc',
    slug: 'devsinc',
    sector: 'Software Services',
    city: 'Lahore',
    funding: '$8M',
    fundingStage: 'Series A',
    founder: 'Hamza Tariq',
    founderTitle: 'CEO & Founder',
    logo: 'https://ui-avatars.com/api/?name=Devsinc&background=F4511E&color=fff&size=128&bold=true',
    description: 'Devsinc is a software development company providing full-stack engineering, AI, and cloud solutions to global clients from Pakistan.',
    founded: '2017',
    website: 'https://devsinc.com',
    employees: 350,
    tags: ['software-services', 'outsourcing', 'AI', 'cloud', 'engineering'],
    fundingRounds: [
      { round: 'Seed', amount: '$2M', date: '2021-03', leadInvestor: 'Pak VC' },
      { round: 'Series A', amount: '$8M', date: '2023-01', leadInvestor: 'Global Ventures' },
    ],
    investors: ['Global Ventures', 'Pak VC'],
  },
  {
    id: '8',
    name: 'RiskCovered',
    slug: 'riskcovered',
    sector: 'InsurTech',
    city: 'Islamabad',
    funding: '$4.5M',
    fundingStage: 'Seed',
    founder: 'Zara Shah',
    founderTitle: 'CEO & Co-Founder',
    logo: 'https://ui-avatars.com/api/?name=RiskCovered&background=00838F&color=fff&size=128&bold=true',
    description: 'RiskCovered provides AI-powered insurance solutions making affordable micro-insurance accessible to underserved communities across Pakistan.',
    founded: '2022',
    website: 'https://riskcovered.pk',
    employees: 40,
    tags: ['insurtech', 'micro-insurance', 'AI', 'financial-inclusion'],
    fundingRounds: [
      { round: 'Pre-Seed', amount: '$0.5M', date: '2022-03', leadInvestor: 'i2i Ventures' },
      { round: 'Seed', amount: '$4.5M', date: '2024-01', leadInvestor: 'Fatima Gobi Ventures' },
    ],
    investors: ['Fatima Gobi Ventures', 'i2i Ventures', 'Pak VC'],
  },
];

export const investors: Investor[] = [
  {
    id: '1',
    name: 'Indus Valley Capital',
    type: 'VC',
    logo: 'https://ui-avatars.com/api/?name=IVC&background=1A237E&color=fff&size=128&bold=true',
    portfolio: ['Bykea', 'Bazaar', 'Airlift', 'TelloTalk'],
    totalInvested: '$120M+',
    website: 'https://indusvalley.capital',
  },
  {
    id: '2',
    name: 'Sarmayacar',
    type: 'VC',
    logo: 'https://ui-avatars.com/api/?name=S&background=0D47A1&color=fff&size=128&bold=true',
    portfolio: ['Bazaar', 'Bykea', 'TelloTalk'],
    totalInvested: '$85M+',
    website: 'https://sarmayacar.com',
  },
  {
    id: '3',
    name: 'Global Ventures',
    type: 'VC',
    logo: 'https://ui-avatars.com/api/?name=GV&background=1B5E20&color=fff&size=128&bold=true',
    portfolio: ['Bykea', 'SadaPay', 'Devsinc', 'TAG Innovation'],
    totalInvested: '$200M+',
    website: 'https://globalventures.fund',
  },
  {
    id: '4',
    name: 'Fatima Gobi Ventures',
    type: 'VC',
    logo: 'https://ui-avatars.com/api/?name=FGV&background=E65100&color=fff&size=128&bold=true',
    portfolio: ['TAG Innovation', 'Airlift', 'RiskCovered'],
    totalInvested: '$45M+',
    website: 'https://fatimagobiventures.com',
  },
  {
    id: '5',
    name: 'i2i Ventures',
    type: 'VC',
    logo: 'https://ui-avatars.com/api/?name=iV&background=4A148C&color=fff&size=128&bold=true',
    portfolio: ['Bykea', 'TAG Innovation', 'RiskCovered'],
    totalInvested: '$30M+',
    website: 'https://i2iventures.com',
  },
  {
    id: '6',
    name: 'Pak VC',
    type: 'Angel',
    logo: 'https://ui-avatars.com/api/?name=PV&background=B71C1C&color=fff&size=128&bold=true',
    portfolio: ['Devsinc', 'RiskCovered'],
    totalInvested: '$15M+',
    website: 'https://pakvc.com',
  },
];

export const users: User[] = [
  { id: '1', name: 'Admin User', email: 'admin@ilmtech.pk', avatar: 'https://i.pravatar.cc/150?u=admin-ilmtech', role: 'admin', joinedAt: '2024-01-15', bookmarks: ['1', '3', '5'], readingList: ['1', '2', '4', '6'] },
  { id: '2', name: 'Ahmed Khan', email: 'ahmed@ilmtech.pk', avatar: 'https://i.pravatar.cc/150?u=ahmed-khan', role: 'editor', joinedAt: '2024-03-20', bookmarks: ['2', '7'], readingList: ['3', '8'] },
  { id: '3', name: 'Fatima Ali', email: 'fatima@ilmtech.pk', avatar: 'https://i.pravatar.cc/150?u=fatima-ali', role: 'editor', joinedAt: '2024-06-10', bookmarks: ['4', '9'], readingList: ['5', '10'] },
  { id: '4', name: 'Usman Raza', email: 'usman@ilmtech.pk', avatar: 'https://i.pravatar.cc/150?u=usman-raza', role: 'contributor', joinedAt: '2025-01-05', bookmarks: ['6', '11'], readingList: ['1', '12'] },
  { id: '5', name: 'Sara Malik', email: 'sara@ilmtech.pk', avatar: 'https://i.pravatar.cc/150?u=sara-malik', role: 'contributor', joinedAt: '2025-04-12', bookmarks: ['8', '13'], readingList: ['2', '14'] },
];

export const comments: Comment[] = [
  { id: '1', articleId: '1', userId: '5', userName: 'Sara Malik', userAvatar: 'https://i.pravatar.cc/150?u=sara-malik', content: 'Great news for Pakistan\'s fintech ecosystem! Bykea\'s Series C will help them scale significantly and bring financial services to underserved areas.', createdAt: '2026-08-20T12:00:00Z', likes: 15 },
  { id: '2', articleId: '1', userId: '4', userName: 'Usman Raza', userAvatar: 'https://i.pravatar.cc/150?u=usman-raza', content: 'Karachi is becoming a real hub for tech investments. The gig economy here is growing faster than anyone expected.', createdAt: '2026-08-20T13:30:00Z', likes: 8 },
  { id: '3', articleId: '2', userId: '3', userName: 'Fatima Ali', userAvatar: 'https://i.pravatar.cc/150?u=fatima-ali', content: 'Finally, a proper cybersecurity framework for government agencies. This was long overdue given the increasing threats we\'ve seen this year.', createdAt: '2026-08-19T10:00:00Z', likes: 22 },
  { id: '4', articleId: '2', userId: '1', userName: 'Admin User', userAvatar: 'https://i.pravatar.cc/150?u=admin-ilmtech', content: 'The 6-month compliance timeline is aggressive. I hope agencies are prepared with the necessary resources and training.', createdAt: '2026-08-19T11:15:00Z', likes: 12 },
  { id: '5', articleId: '3', userId: '2', userName: 'Ahmed Khan', userAvatar: 'https://i.pravatar.cc/150?u=ahmed-khan', content: 'AI in healthcare could save thousands of lives in rural areas where specialist doctors are scarce. This is exactly what Pakistan needs.', createdAt: '2026-08-18T16:00:00Z', likes: 35 },
  { id: '6', articleId: '3', userId: '5', userName: 'Sara Malik', userAvatar: 'https://i.pravatar.cc/150?u=sara-malik', content: 'Would love to see more details about the specific AI algorithms being used and their accuracy rates compared to human doctors.', createdAt: '2026-08-18T17:30:00Z', likes: 7 },
  { id: '7', articleId: '4', userId: '4', userName: 'Usman Raza', userAvatar: 'https://i.pravatar.cc/150?u=usman-raza', content: '5G in Lahore is a game changer. When can we expect it in other cities like Islamabad and Faisalabad?', createdAt: '2026-08-17T11:00:00Z', likes: 18 },
  { id: '8', articleId: '4', userId: '2', userName: 'Ahmed Khan', userAvatar: 'https://i.pravatar.cc/150?u=ahmed-khan', content: 'The speed tests are impressive! 10 Gbps is incredible. This could really accelerate our digital economy.', createdAt: '2026-08-17T12:45:00Z', likes: 14 },
  { id: '9', articleId: '5', userId: '3', userName: 'Fatima Ali', userAvatar: 'https://i.pravatar.cc/150?u=fatima-ali', content: 'The camera improvements sound amazing, but at PKR 349,000 the price is still too high for most Pakistanis.', createdAt: '2026-08-16T14:00:00Z', likes: 25 },
  { id: '10', articleId: '5', userId: '1', userName: 'Admin User', userAvatar: 'https://i.pravatar.cc/150?u=admin-ilmtech', content: 'Battery life improvements are what I care about most. How does it compare to the iPhone 16 Pro Max?', createdAt: '2026-08-16T15:30:00Z', likes: 9 },
];

export const TAGS: Tag[] = [
  { name: 'AI', count: 45, slug: 'ai' },
  { name: 'fintech', count: 38, slug: 'fintech' },
  { name: 'cybersecurity', count: 32, slug: 'cybersecurity' },
  { name: 'startups', count: 52, slug: 'startups' },
  { name: '5G', count: 18, slug: '5g' },
  { name: 'telecom', count: 22, slug: 'telecom' },
  { name: 'data-protection', count: 15, slug: 'data-protection' },
  { name: 'cloud', count: 20, slug: 'cloud' },
  { name: 'review', count: 28, slug: 'review' },
  { name: 'smartphone', count: 24, slug: 'smartphone' },
  { name: 'startup-funding', count: 41, slug: 'startup-funding' },
  { name: 'healthcare', count: 12, slug: 'healthcare' },
  { name: 'education', count: 16, slug: 'education' },
  { name: 'IoT', count: 14, slug: 'iot' },
  { name: 'machine-learning', count: 19, slug: 'machine-learning' },
  { name: 'banking', count: 21, slug: 'banking' },
  { name: 'privacy', count: 17, slug: 'privacy' },
  { name: 'apple', count: 30, slug: 'apple' },
  { name: 'samsung', count: 26, slug: 'samsung' },
  { name: 'agritech', count: 11, slug: 'agritech' },
];

